mode: debug
log_level: debug
log_path: logs
log_level_addr: :4245
log_level_pattern: /log/level

app:
  # JWT Configuration
  jwt_secret: xxx  # $(openssl rand -base64 32)
  jwt_access_duration: 15   # Access token duration in minutes (default: 15)
  jwt_refresh_duration: 7   # Refresh token duration in days (default: 7)
  upload_path: uploads
  geoip_db_path: config/GeoLite2-City.mmdb

http:
  addr: :8080

postgres:
  host: 127.0.0.1
  port: 5433
  username: postgres
  password: 123456
  dbname: blog
  ssl_mode: disable
  migrate: true
  max_open_conns: 100
  max_idle_conns: 10
  # seconds
  conn_max_life_time: 86400       # 24*60*60 seconds = 1 day
